import { ProductTypeEnum } from "../../utils/enum";

export default defineEventHandler(
  async (event): Promise<WhereByApiResponse> => {
    const {
      CountryCode,
      ProductType,
      ClassKey,
      SaleTypeValue,
      PageNow,
      CityCode,
    }: WhereByApiParams = await readBody(event);

    if (CountryCode === 105134000) {
      if (ProductType === ProductTypeEnum.consumer) {
        if (SaleTypeValue === 1) {
          return {
            NowPage: 1,
            NowSaleType: "1",
            TotalPage: 1,
            ListItems: [
              {
                Id: 442,
                ImagePath: "/FileUpload/Reseller/442.JPG",
                Name: "青雲國際科技股份有限公司",
                Tel: ["02-82273277"],
                TelCountryCode: "886",
                Email: null,
                Address: "新北市中和區中正路716號6樓",
                ProductLines: [
                  "主機板",
                  "顯示卡",
                  "筆記型電腦",
                  "顯示器",
                  "個人電腦",
                  "BRIX (迷你準系統電腦)",
                  "鍵盤",
                  "滑鼠",
                  "耳機",
                  "電競椅",
                  "機殼",
                  "散熱產品",
                  "電源供應器",
                  "記憶體",
                  "固態硬碟 (SSD)",
                ],
                Remark: "",
                UrlPath: "https://www.albatron.com.tw/",
                GeoAxisX: 24.997304916381836,
                GeoAxisY: 121.48560333251953,
              },
              {
                Id: 52497,
                ImagePath: "/FileUpload/Reseller/52497.jpg",
                Name: "威健實業股份有限公司",
                Tel: ["2-26590202"],
                TelCountryCode: "886",
                Email: "",
                Address: "台北市內湖區內湖路一段308號11樓",
                ProductLines: ["BRIX (迷你準系統電腦)"],
                Remark: "",
                UrlPath: "https://www.weikeng.com.tw/",
                GeoAxisX: 0,
                GeoAxisY: 0,
              },
              {
                Id: 759,
                ImagePath: "/FileUpload/Reseller/759.jpg",
                Name: "捷元股份有限公司",
                Tel: ["02-27956677"],
                TelCountryCode: "886",
                Email: "",
                Address: "台北市內湖區瑞光路66巷36號",
                ProductLines: [
                  "主機板",
                  "顯示卡",
                  "筆記型電腦",
                  "顯示器",
                  "個人電腦",
                  "鍵盤",
                  "滑鼠",
                  "耳機",
                  "電競椅",
                  "機殼",
                  "散熱產品",
                  "電源供應器",
                  "記憶體",
                  "固態硬碟 (SSD)",
                ],
                Remark: "",
                UrlPath: "http://www.gcnc-group.com",
                GeoAxisX: 25.07008171081543,
                GeoAxisY: 121.58132171630859,
              },
              {
                Id: 53614,
                ImagePath: "/FileUpload/Reseller/53614.png",
                Name: "聯強國際",
                Tel: ["2506-3320"],
                TelCountryCode: "886",
                Email: "",
                Address: "台北市民生東路3段75號4樓",
                ProductLines: ["BRIX (迷你準系統電腦)"],
                Remark: "",
                UrlPath: "http://www.synnex.com.tw/",
                GeoAxisX: 25.058183670043945,
                GeoAxisY: 121.54388427734375,
              },
              {
                Id: 54130,
                ImagePath: "/FileUpload/Reseller/54130.jpg",
                Name: "聯強國際",
                Tel: ["02-25063320"],
                TelCountryCode: "886",
                Email: "",
                Address: "臺北市中山區民生東路三段75號4樓",
                ProductLines: [
                  "主機板",
                  "顯示卡",
                  "筆記型電腦",
                  "顯示器",
                  "個人電腦",
                  "鍵盤",
                  "滑鼠",
                  "耳機",
                  "電競椅",
                  "機殼",
                  "散熱產品",
                  "電源供應器",
                  "記憶體",
                  "固態硬碟 (SSD)",
                ],
                Remark: "",
                UrlPath: "http://www.synnex-grp.com/tw/home",
                GeoAxisX: 25.058183670043945,
                GeoAxisY: 121.54388427734375,
              },
            ],
          };
        }

        if (SaleTypeValue === 2) {
          return {
            NowPage: 1,
            NowSaleType: "2",
            TotalPage: 9,
            ListItems: [
              {
                Id: 54330,
                ImagePath: "/FileUpload/Reseller/54330.png",
                Name: "AORUS形象旗艦館-台南e01門市",
                Tel: ["06-7032909"],
                TelCountryCode: "886",
                Email: "",
                Address: "台南市北門路一段226號1F (台南e01數位商場A5櫃)",
                ProductLines: [
                  "主機板",
                  "顯示卡",
                  "筆記型電腦",
                  "顯示器",
                  "個人電腦",
                  "鍵盤",
                  "滑鼠",
                  "耳機",
                  "電競椅",
                  "機殼",
                  "散熱產品",
                  "電源供應器",
                  "記憶體",
                  "固態硬碟 (SSD)",
                ],
                Remark: "",
                UrlPath: "",
                GeoAxisX: 22.9943324,
                GeoAxisY: 120.2119105,
              },
              {
                Id: 54190,
                ImagePath: "/FileUpload/Reseller/54190.jpg",
                Name: "三井3C-八德店",
                Tel: ["03-2180026"],
                TelCountryCode: "886",
                Email: "",
                Address: "桃園市八德區介壽路一段976、978號1樓",
                ProductLines: ["筆記型電腦", "顯示器"],
                Remark: "",
                UrlPath: "",
                GeoAxisX: 24.958000183105469,
                GeoAxisY: 121.29914855957031,
              },
              {
                Id: 54131,
                ImagePath: "/FileUpload/Reseller/54131.jpg",
                Name: "三井3C-三創門市技嘉專區",
                Tel: ["02 -23413746"],
                TelCountryCode: "886",
                Email: "",
                Address: "台北市中正區市民大道三段2號2號樓 R214-5",
                ProductLines: ["筆記型電腦", "顯示器"],
                Remark: "",
                UrlPath: "",
                GeoAxisX: 25.045490264892578,
                GeoAxisY: 121.5311279296875,
              },
              {
                Id: 54014,
                ImagePath: "/FileUpload/Reseller/54014.jpg",
                Name: "三井3C-中壢NOVA二店",
                Tel: ["03-4922998"],
                TelCountryCode: "886",
                Email: "",
                Address: "桃園市中壢區中正路389號1樓103室",
                ProductLines: ["筆記型電腦", "顯示器"],
                Remark: "",
                UrlPath: "",
                GeoAxisX: 24.955472946166992,
                GeoAxisY: 121.21532440185547,
              },
              {
                Id: 54505,
                ImagePath: "/FileUpload/Reseller/54505.png",
                Name: "三井3C-中壢NOVA三店",
                Tel: ["03-3475609"],
                TelCountryCode: "886",
                Email: "",
                Address: "桃園市桃園區復興路99號1樓121.122室",
                ProductLines: ["筆記型電腦", "顯示器"],
                Remark: "",
                UrlPath: "",
                GeoAxisX: 24.99048,
                GeoAxisY: 121.3137222,
              },
              {
                Id: 54189,
                ImagePath: "/FileUpload/Reseller/54189.jpg",
                Name: "三井3C-中壢NOVA店",
                Tel: ["03-4016710"],
                TelCountryCode: "886",
                Email: "",
                Address: "桃園市中正路389號2樓217室",
                ProductLines: ["筆記型電腦", "顯示器"],
                Remark: "",
                UrlPath: "",
                GeoAxisX: 24.955501556396484,
                GeoAxisY: 121.21544647216797,
              },
              {
                Id: 54016,
                ImagePath: "/FileUpload/Reseller/54016.jpg",
                Name: "三井3C-台中NOVA三店",
                Tel: ["04-23298429"],
                TelCountryCode: "886",
                Email: "",
                Address: "台中市西區公益路123號1樓",
                ProductLines: ["筆記型電腦", "顯示器"],
                Remark: "",
                UrlPath: "",
                GeoAxisX: 24.150711059570313,
                GeoAxisY: 120.66546630859375,
              },
              {
                Id: 54188,
                ImagePath: "/FileUpload/Reseller/54188.jpg",
                Name: "三井3C-台中NOVA店",
                Tel: ["04-23298337"],
                TelCountryCode: "886",
                Email: "",
                Address: "臺中市西英才路510號地下1樓B16室",
                ProductLines: ["筆記型電腦", "顯示器"],
                Remark: "",
                UrlPath: "",
                GeoAxisX: 24.151021957397461,
                GeoAxisY: 120.66499328613281,
              },
              {
                Id: 54511,
                ImagePath: "/FileUpload/Reseller/54511.png",
                Name: "三井3C-台中東海店",
                Tel: ["04-24651199"],
                TelCountryCode: "886",
                Email: "",
                Address: "臺中市西屯區台灣大道四段1086號1樓115室 (三井3C)",
                ProductLines: ["筆記型電腦", "顯示器"],
                Remark: "",
                UrlPath: "",
                GeoAxisX: 24.1841332,
                GeoAxisY: 120.614969,
              },
              {
                Id: 54522,
                ImagePath: "/FileUpload/Reseller/54522.png",
                Name: "三井3C-永華店",
                Tel: ["06-2993479"],
                TelCountryCode: "886",
                Email: "",
                Address: "台南市中西區永華路一段301號",
                ProductLines: ["筆記型電腦", "顯示器"],
                Remark: "",
                UrlPath: "",
                GeoAxisX: 22.988508,
                GeoAxisY: 120.188489,
              },
              {
                Id: 54013,
                ImagePath: "/FileUpload/Reseller/54013.jpg",
                Name: "三井3C-光華五店",
                Tel: ["02-23519609"],
                TelCountryCode: "886",
                Email: "",
                Address: "台北市中正區市民大道三段8號1樓X04櫃",
                ProductLines: ["筆記型電腦", "顯示器"],
                Remark: "",
                UrlPath: "",
                GeoAxisX: 25.045036315917969,
                GeoAxisY: 121.53192901611328,
              },
              {
                Id: 54193,
                ImagePath: "/FileUpload/Reseller/54193.jpg",
                Name: "三井3C-板橋店",
                Tel: ["02-29575409"],
                TelCountryCode: "886",
                Email: "",
                Address: "新北市板橋區重慶路66號1樓",
                ProductLines: ["筆記型電腦", "顯示器"],
                Remark: "",
                UrlPath: "",
                GeoAxisX: 25.006603240966797,
                GeoAxisY: 121.46158599853516,
              },
              {
                Id: 54191,
                ImagePath: "/FileUpload/Reseller/54191.jpg",
                Name: "三井3C-南崁店",
                Tel: ["03-2128160"],
                TelCountryCode: "886",
                Email: "",
                Address: "桃園市蘆竹區中正路287、289號1樓",
                ProductLines: ["筆記型電腦", "顯示器"],
                Remark: "",
                UrlPath: "",
                GeoAxisX: 25.047361373901367,
                GeoAxisY: 121.29188537597656,
              },
              {
                Id: 54017,
                ImagePath: "/FileUpload/Reseller/54017.jpg",
                Name: "三井3C-高雄建國二店",
                Tel: ["07-2362855"],
                TelCountryCode: "886",
                Email: "",
                Address: "高雄市三民區建國二路96號1樓",
                ProductLines: ["筆記型電腦", "顯示器"],
                Remark: "",
                UrlPath: "",
                GeoAxisX: 22.637655258178711,
                GeoAxisY: 120.30989837646484,
              },
              {
                Id: 54523,
                ImagePath: "/FileUpload/Reseller/54523.png",
                Name: "三井3C-彩虹店",
                Tel: ["06-2239738"],
                TelCountryCode: "886",
                Email: "",
                Address: "台南市東區成大里30鄰北門路一段250號1樓 A-02室",
                ProductLines: ["筆記型電腦", "顯示器"],
                Remark: "",
                UrlPath: "",
                GeoAxisX: 22.9947718,
                GeoAxisY: 120.2119604,
              },
              {
                Id: 54015,
                ImagePath: "/FileUpload/Reseller/54015.jpg",
                Name: "三井3C-新竹NOVA店",
                Tel: ["03-572-5818"],
                TelCountryCode: "886",
                Email: "",
                Address: "新竹市東區立功里8鄰光復路二段194巷3號2樓222室",
                ProductLines: ["筆記型電腦", "顯示器"],
                Remark: "",
                UrlPath: "",
                GeoAxisX: 24.794477462768555,
                GeoAxisY: 121.00075531005859,
              },
              {
                Id: 54520,
                ImagePath: "/FileUpload/Reseller/54520.png",
                Name: "三井3C-嘉義評好店",
                Tel: ["05-2226535"],
                TelCountryCode: "886",
                Email: "",
                Address: "嘉義市西區新榮路236號1樓101櫃",
                ProductLines: ["筆記型電腦", "顯示器"],
                Remark: "",
                UrlPath: "",
                GeoAxisX: 23.4802691,
                GeoAxisY: 120.4440778,
              },
              {
                Id: 54192,
                ImagePath: "/FileUpload/Reseller/54192.jpg",
                Name: "三井3C-龍潭店",
                Tel: ["03-4702192"],
                TelCountryCode: "886",
                Email: "",
                Address: "桃園市龍潭區龍潭里21鄰中正路164號1樓",
                ProductLines: ["筆記型電腦", "顯示器"],
                Remark: "",
                UrlPath: "",
                GeoAxisX: 24.865665435791016,
                GeoAxisY: 121.216796875,
              },
              {
                Id: 54194,
                ImagePath: "/FileUpload/Reseller/54194.jpg",
                Name: "三井3C-鴻金寶店",
                Tel: ["02-22058050"],
                TelCountryCode: "886",
                Email: "",
                Address: "新北市新莊區四維路3號1樓",
                ProductLines: ["筆記型電腦", "顯示器"],
                Remark: "",
                UrlPath: "",
                GeoAxisX: 25.025096893310547,
                GeoAxisY: 121.42404174804688,
              },
              {
                Id: 54181,
                ImagePath: "",
                Name: "三瑛科技",
                Tel: ["03-5727671"],
                TelCountryCode: "886",
                Email: "",
                Address: "新竹市光復路二段200號 (150 櫃)",
                ProductLines: [
                  "主機板",
                  "顯示卡",
                  "個人電腦",
                  "鍵盤",
                  "滑鼠",
                  "耳機",
                  "電競椅",
                  "機殼",
                  "散熱產品",
                  "電源供應器",
                  "記憶體",
                  "固態硬碟 (SSD)",
                ],
                Remark: "",
                UrlPath: "",
                GeoAxisX: 0,
                GeoAxisY: 0,
              },
              {
                Id: 54183,
                ImagePath: "",
                Name: "太極數位",
                Tel: ["07-2355099"],
                TelCountryCode: "886",
                Email: "",
                Address: "高雄市三民區建國二路140號",
                ProductLines: [
                  "主機板",
                  "顯示卡",
                  "個人電腦",
                  "機殼",
                  "散熱產品",
                  "電源供應器",
                  "記憶體",
                  "固態硬碟 (SSD)",
                ],
                Remark: "",
                UrlPath: "",
                GeoAxisX: 0,
                GeoAxisY: 0,
              },
              {
                Id: 815,
                ImagePath: "/FileUpload/Reseller/815.jpg",
                Name: "文生實業有限公司",
                Tel: ["02-23923422"],
                TelCountryCode: "886",
                Email: "",
                Address: "台北市新生南路1段6號B2-30",
                ProductLines: [
                  "主機板",
                  "顯示卡",
                  "個人電腦",
                  "鍵盤",
                  "滑鼠",
                  "耳機",
                  "電競椅",
                  "機殼",
                  "散熱產品",
                  "電源供應器",
                  "記憶體",
                  "固態硬碟 (SSD)",
                ],
                Remark: "",
                UrlPath: "",
                GeoAxisX: 25.044023513793945,
                GeoAxisY: 121.53262329101563,
              },
              {
                Id: 47135,
                ImagePath: "",
                Name: "本龍",
                Tel: ["06-2234202"],
                TelCountryCode: "886",
                Email: null,
                Address: "台南市北門路一段216號",
                ProductLines: [
                  "主機板",
                  "顯示卡",
                  "顯示器",
                  "個人電腦",
                  "鍵盤",
                  "滑鼠",
                  "耳機",
                  "電競椅",
                  "機殼",
                  "散熱產品",
                  "電源供應器",
                  "記憶體",
                  "固態硬碟 (SSD)",
                ],
                Remark: "",
                UrlPath: "",
                GeoAxisX: 22.994122,
                GeoAxisY: 120.211902,
              },
              {
                Id: 931,
                ImagePath: "/FileUpload/Reseller/931.jpg",
                Name: "永昌資訊",
                Tel: ["02-2397-2336"],
                TelCountryCode: "886",
                Email: "",
                Address: "台北市八德路一段98號1樓",
                ProductLines: [
                  "筆記型電腦",
                  "顯示器",
                  "鍵盤",
                  "滑鼠",
                  "耳機",
                  "電競椅",
                ],
                Remark: "",
                UrlPath: "",
                GeoAxisX: 25.044086456298828,
                GeoAxisY: 121.53233337402344,
              },
            ],
          };
        }

        if (SaleTypeValue === 4) {
          return {
            NowPage: 1,
            NowSaleType: "4",
            TotalPage: 1,
            ListItems: [
              {
                Id: 53117,
                ImagePath: "https://gigabyte.com/FileUpload/Reseller/53117.jpg",
                Name: "MOMO",
                Tel: [],
                TelCountryCode: "",
                Email: "",
                Address: "",
                ProductLines: [
                  "主機板",
                  "顯示卡",
                  "筆記型電腦",
                  "顯示器",
                  "個人電腦",
                  "鍵盤",
                  "滑鼠",
                  "耳機",
                  "電競椅",
                  "機殼",
                  "散熱產品",
                  "電源供應器",
                  "記憶體",
                  "固態硬碟 (SSD)",
                ],
                Remark: "",
                UrlPath:
                  "https://www.momoshop.com.tw/category/LgrpCategory.jsp?l_code=2160000000\u0026mdiv=1000900000-bt_5_023_09-bt_5_023_09_P1_20_e1\u0026ctype=B",
                GeoAxisX: 0,
                GeoAxisY: 0,
              },
              {
                Id: 668,
                ImagePath: "https://gigabyte.com/FileUpload/Reseller/53117.jpg",
                Name: "PChome 24hrs",
                Tel: [],
                TelCountryCode: "886",
                Email: "",
                Address: "",
                ProductLines: [
                  "主機板",
                  "顯示卡",
                  "筆記型電腦",
                  "顯示器",
                  "個人電腦",
                  "鍵盤",
                  "滑鼠",
                  "耳機",
                  "電競椅",
                  "機殼",
                  "散熱產品",
                  "電源供應器",
                  "記憶體",
                  "固態硬碟 (SSD)",
                ],
                Remark: "",
                UrlPath:
                  "https://ecshweb.pchome.com.tw/search/v3.3/?q=%E6%8A%80%E5%98%89",
                GeoAxisX: 25.028388977050781,
                GeoAxisY: 121.54906463623047,
              },
              {
                Id: 669,
                ImagePath: "https://gigabyte.com/FileUpload/Reseller/53117.jpg",
                Name: "YAHOO購物中心",
                Tel: [],
                TelCountryCode: "886",
                Email: "",
                Address: "",
                ProductLines: ["筆記型電腦", "顯示器"],
                Remark: "",
                UrlPath:
                  "https://tw.buy.yahoo.com/act/activity/gigabyteforever.html",
                GeoAxisX: 0,
                GeoAxisY: 0,
              },
              {
                Id: 54429,
                ImagePath: "https://gigabyte.com/FileUpload/Reseller/53117.jpg",
                Name: "南紡購物中心",
                Tel: [],
                TelCountryCode: "886",
                Email: "",
                Address: "",
                ProductLines: [
                  "主機板",
                  "顯示卡",
                  "筆記型電腦",
                  "顯示器",
                  "個人電腦",
                  "鍵盤",
                  "滑鼠",
                  "耳機",
                  "電競椅",
                  "機殼",
                  "散熱產品",
                  "電源供應器",
                  "記憶體",
                  "固態硬碟 (SSD)",
                ],
                Remark: "",
                UrlPath:
                  "https://shopping.pchome.com.tw/activity/campaign/C615903245",
                GeoAxisX: 0,
                GeoAxisY: 0,
              },
              {
                Id: 36,
                ImagePath: "https://gigabyte.com/FileUpload/Reseller/53117.jpg",
                Name: "燦坤實業股份有限公司",
                Tel: [],
                TelCountryCode: "886",
                Email: "",
                Address:
                  "5F., No.331, Sec. 1, Ti-Ding Blvd., Nei-Hu Dist., Taipei City 114, Taiwan (R.O.C.)",
                ProductLines: ["筆記型電腦", "顯示器"],
                Remark: "",
                UrlPath:
                  "https://www.tkec.com.tw/search.aspx?q=%E6%8A%80%E5%98%89\u0026bid=gigabyte\u0026ec=search_brand",
                GeoAxisX: 25.062709808349609,
                GeoAxisY: 121.57302093505859,
              },
              {
                Id: 53169,
                ImagePath: "https://gigabyte.com/FileUpload/Reseller/53117.jpg",
                Name: "驊哥電腦",
                Tel: [],
                TelCountryCode: "",
                Email: "",
                Address: "",
                ProductLines: ["筆記型電腦", "顯示器"],
                Remark: "",
                UrlPath:
                  "https://www.huahuacomputer.com.tw/pages/gigabyte-gaming",
                GeoAxisX: 0,
                GeoAxisY: 0,
              },
            ],
          };
        }
      }

      if (ProductType === ProductTypeEnum.enterprise) {
        return {
          NowPage: 1,
          NowSaleType: "1",
          TotalPage: 1,
          ListItems: [
            {
              Id: 53615,
              ImagePath: "/FileUpload/Reseller/53615.jpg",
              Name: "青雲國際科技股份有限公司",
              Tel: ["2-8227-3277 "],
              TelCountryCode: "886",
              Email: "sales@albatron.com.tw",
              Address: "新北市中和區中正路716號6 樓",
              ProductLines: [
                "伺服器主機板",
                "R 系列伺服器",
                "H 系列伺服器",
                "G 系列伺服器",
                "E 系列伺服器",
                "S 系列伺服器",
                "W 系列伺服器",
                "伺服器配件",
              ],
              Remark: "",
              UrlPath: "https://www.albatron.com.tw",
              GeoAxisX: 24.997304916381836,
              GeoAxisY: 121.48560333251953,
            },
            {
              Id: 52497,
              ImagePath: "/FileUpload/Reseller/52497.jpg",
              Name: "威健實業股份有限公司",
              Tel: ["2-26590202"],
              TelCountryCode: "886",
              Email: "",
              Address: "台北市內湖區內湖路一段308號11樓",
              ProductLines: [
                "伺服器主機板",
                "R 系列伺服器",
                "H 系列伺服器",
                "G 系列伺服器",
                "E 系列伺服器",
                "S 系列伺服器",
                "W 系列伺服器",
                "伺服器配件",
              ],
              Remark: "",
              UrlPath: "https://www.weikeng.com.tw/",
              GeoAxisX: 0,
              GeoAxisY: 0,
            },
            {
              Id: 53760,
              ImagePath: "/FileUpload/Reseller/53760.png",
              Name: "建達國際股份有限公司",
              Tel: ["2219-1600"],
              TelCountryCode: "886",
              Email: "",
              Address: "新北市新店區中正路531號5樓",
              ProductLines: [
                "伺服器主機板",
                "R 系列伺服器",
                "H 系列伺服器",
                "G 系列伺服器",
                "E 系列伺服器",
                "S 系列伺服器",
                "W 系列伺服器",
                "伺服器配件",
              ],
              Remark: "",
              UrlPath: "http://www.xander.com.tw/user2/home/",
              GeoAxisX: 0,
              GeoAxisY: 0,
            },
            {
              Id: 53614,
              ImagePath: "/FileUpload/Reseller/53614.png",
              Name: "聯強國際",
              Tel: ["2506-3320"],
              TelCountryCode: "886",
              Email: "",
              Address: "台北市民生東路3段75號4樓",
              ProductLines: [
                "伺服器主機板",
                "R 系列伺服器",
                "H 系列伺服器",
                "G 系列伺服器",
                "E 系列伺服器",
                "S 系列伺服器",
                "W 系列伺服器",
                "伺服器配件",
              ],
              Remark: "",
              UrlPath: "http://www.synnex.com.tw/",
              GeoAxisX: 25.058183670043945,
              GeoAxisY: 121.54388427734375,
            },
          ],
        };
      }
    }

    if (CountryCode === 101142000) {
      if (ProductType === ProductTypeEnum.consumer) {
        if (SaleTypeValue === 1) {
          return {
            NowPage: 1,
            NowSaleType: "1",
            TotalPage: 1,
            ListItems: [
              {
                Id: 98,
                ImagePath: "/FileUpload/Reseller/98.gif",
                Name: "Newegg",
                Tel: ["800390-1119"],
                TelCountryCode: "1",
                Email: "",
                Address: "17708 Rowland Street, City of Industry, CA 91748",
                ProductLines: [
                  "Motherboard",
                  "Graphics Card",
                  "Laptop",
                  "Monitors",
                  "BRIX (Mini-PC Barebone)",
                  "Keyboard",
                  "Mouse",
                  "PC Case",
                ],
                Remark: "",
                UrlPath:
                  "https://www.newegg.com/p/pl?d=gigabyte\u0026N=50001314%204841",
                GeoAxisX: 34.000885009765625,
                GeoAxisY: -117.91836547851563,
              },
              {
                Id: 84,
                ImagePath: "/FileUpload/Reseller/84.gif",
                Name: "ASI",
                Tel: ["800-2000274"],
                TelCountryCode: "1",
                Email: "",
                Address: "48289 Fremont Blvd., Fremont, CA 94538",
                ProductLines: [
                  "Motherboard",
                  "Graphics Card",
                  "Laptop",
                  "PC Case",
                ],
                Remark: "",
                UrlPath: "http://www.asipartner.com/",
                GeoAxisX: 37.468280792236328,
                GeoAxisY: -121.93682098388672,
              },
              {
                Id: 89,
                ImagePath: "/FileUpload/Reseller/89.jpg",
                Name: "D\u0026H",
                Tel: ["1-800-877-1200"],
                TelCountryCode: "1",
                Email: null,
                Address:
                  "2525 North Seventh Street, PO Box 5967, Harrisburg, PA 17110-0967",
                ProductLines: ["Motherboard", "Graphics Card", "PC Case"],
                Remark: "",
                UrlPath: "http://www.dandh.com",
                GeoAxisX: 40.2886669,
                GeoAxisY: -76.89016,
              },
              {
                Id: 543,
                ImagePath: "/FileUpload/Reseller/543.jpg",
                Name: "Ingram Micro",
                Tel: ["800-456-8000"],
                TelCountryCode: "1",
                Email: "",
                Address: "1600 E. St. Andrew Place, Snta Ana, CA 92705-4926",
                ProductLines: ["Motherboard", "Graphics Card", "PC Case"],
                Remark: "",
                UrlPath: "http://www.ingrammicro.com",
                GeoAxisX: 33.722396850585938,
                GeoAxisY: -117.84828186035156,
              },
              {
                Id: 54222,
                ImagePath: "/FileUpload/Reseller/54222.png",
                Name: "IT Creations",
                Tel: ["800-983-5318"],
                TelCountryCode: "1",
                Email: "sales@itcreations.com",
                Address: "9142 Independence Ave, Chatsworth, CA 91311, USA",
                ProductLines: ["Motherboard"],
                Remark: "",
                UrlPath: "https://www.itcreations.com/",
                GeoAxisX: 34.237030029296875,
                GeoAxisY: -118.59030151367188,
              },
              {
                Id: 93,
                ImagePath: "/FileUpload/Reseller/93.jpg",
                Name: "Leadertech",
                Tel: ["630238-9988"],
                TelCountryCode: "1",
                Email: null,
                Address: "210 Mittel Drive, Wood Dale, IL 60191",
                ProductLines: ["Motherboard", "PC Case"],
                Remark: "",
                UrlPath: "https://www.leadertechusa.com/",
                GeoAxisX: 41.975624084472656,
                GeoAxisY: -87.985076904296875,
              },
              {
                Id: 95,
                ImagePath: "/FileUpload/Reseller/95.gif",
                Name: "MA Labs",
                Tel: ["855-962-5227"],
                TelCountryCode: "1",
                Email: "sales@malabs.com",
                Address: "2075 North Capital Avenue, San Jose, CA 95132",
                ProductLines: ["Motherboard", "Graphics Card"],
                Remark: "",
                UrlPath: "https://www.malabs.com/",
                GeoAxisX: 37.405731201171875,
                GeoAxisY: -121.8868408203125,
              },
              {
                Id: 49978,
                ImagePath: "/FileUpload/Reseller/49978.jpg",
                Name: "Max Group",
                Tel: ["800 256 9040"],
                TelCountryCode: "1",
                Email: null,
                Address: "17011 Green Drive, City of Industry, CA 91745",
                ProductLines: ["Motherboard"],
                Remark: "",
                UrlPath: "http://www.maxgroup.com/",
                GeoAxisX: 34.003592,
                GeoAxisY: -117.937127,
              },
              {
                Id: 51248,
                ImagePath: "/FileUpload/Reseller/51248.jpg",
                Name: "The Wise Computer",
                Tel: ["305-594-5725"],
                TelCountryCode: "1",
                Email: null,
                Address: "3515 NW 114 Avenue, Doral, FL 33178.",
                ProductLines: [
                  "Motherboard",
                  "Graphics Card",
                  "BRIX (Mini-PC Barebone)",
                ],
                Remark: "786-357-0379",
                UrlPath: "http://www.wisecomputer.com/",
                GeoAxisX: 25.8065047,
                GeoAxisY: -80.3808375,
              },
            ],
          };
        }

        if (SaleTypeValue === 3) {
          return {
            NowPage: 1,
            NowSaleType: "3",
            TotalPage: 1,
            ListItems: [
              {
                Id: 47192,
                ImagePath: "/FileUpload/Reseller/47192.jpg",
                Name: "Altex",
                Tel: ["210-655-8882"],
                TelCountryCode: "1",
                Email: null,
                Address: "11342 IH35 North San Antonio, TX 78233",
                ProductLines: ["Motherboard"],
                Remark:
                  'Website: \u003ca href="https://www.altex.com/AdvancedSearchE.aspx?k=gigabyte" target="_blank"\u003ehttp://www.altex.com/\u003c/a\u003e',
                UrlPath: "",
                GeoAxisX: 29.560052,
                GeoAxisY: -98.3636131,
              },
              {
                Id: 54726,
                ImagePath: "/FileUpload/Reseller/54726.png",
                Name: "AntOnline",
                Tel: [],
                TelCountryCode: "1",
                Email: "",
                Address: "",
                ProductLines: ["Motherboard", "Graphics Card", "Laptop"],
                Remark: "",
                UrlPath: "https://www.antonline.com/",
                GeoAxisX: 0,
                GeoAxisY: 0,
              },
              {
                Id: 867,
                ImagePath: "/FileUpload/Reseller/867.png",
                Name: "Central Computers-Santa Clara",
                Tel: ["408-248-5888"],
                TelCountryCode: "1",
                Email: "",
                Address: "3777 Stevens Creek Blvd Santa Clara, CA 95051",
                ProductLines: ["Motherboard"],
                Remark:
                  'Website: \u003ca href="http://www.centralcomputers.com/search.aspx?SearchTerm=gigabyte\u0026section=-133942-" target="_blank"\u003ehttp://www.centralcomputers.com/\u003c/a\u003e\u003cbr\u003e\u003cbr\u003e',
                UrlPath: "",
                GeoAxisX: 37.324024200439453,
                GeoAxisY: -121.96800994873047,
              },
              {
                Id: 91,
                ImagePath: "/FileUpload/Reseller/91.jpg",
                Name: "Fry\u0027s Electronics",
                Tel: ["877-688-7678"],
                TelCountryCode: "1",
                Email: null,
                Address: "600 E. Brokaw Road, San Jose, CA 95112",
                ProductLines: ["BRIX (Mini-PC Barebone)"],
                Remark:
                  'Website: \u003ca href="http://www.frys.com/search?search_type=regular\u0026sqxts=1\u0026cat=\u0026query_string=gigabyte" target="_blank"\u003ehttp://www.frys.com\u003c/a\u003e\u003cbr\u003e\u003cbr\u003e',
                UrlPath: "",
                GeoAxisX: 37.38072,
                GeoAxisY: -121.9077499,
              },
              {
                Id: 96,
                ImagePath: "/FileUpload/Reseller/96.jpg",
                Name: "Micro Center",
                Tel: ["614-326-8500"],
                TelCountryCode: "1",
                Email: "",
                Address: "",
                ProductLines: [
                  "Motherboard",
                  "Graphics Card",
                  "Laptop",
                  "Monitors",
                  "BRIX (Mini-PC Barebone)",
                  "PC Case",
                ],
                Remark:
                  'Website: \u003ca href="http://www.microcenter.com/search/search_results.aspx?N=4294965873" target="_blank"\u003ehttp://www.microcenter.com\u003c/a\u003e',
                UrlPath: "https://www.microcenter.com/",
                GeoAxisX: 40.060329437255859,
                GeoAxisY: -83.041343688964844,
              },
              {
                Id: 253,
                ImagePath: "/FileUpload/Reseller/253.jpg",
                Name: "Milwaukee PC",
                Tel: ["414332-0874"],
                TelCountryCode: "1",
                Email: null,
                Address: "3900 N. Sherburn Place, Shorewood, WI 53211",
                ProductLines: ["Motherboard"],
                Remark: "",
                UrlPath: "http://www.milwaukeepc.com",
                GeoAxisX: 43.0884352,
                GeoAxisY: -87.8953438,
              },
            ],
          };
        }

        if (SaleTypeValue === 4) {
          return {
            NowPage: 1,
            NowSaleType: "4",
            TotalPage: 2,
            ListItems: [
              {
                Id: 1347,
                ImagePath: "/FileUpload/Reseller/1347.jpg",
                Name: "Amazon.com",
                Tel: ["866-2161072"],
                TelCountryCode: "1",
                Email: "",
                Address: "",
                ProductLines: [
                  "Motherboard",
                  "Graphics Card",
                  "Laptop",
                  "Monitors",
                  "BRIX (Mini-PC Barebone)",
                  "Keyboard",
                  "Mouse",
                ],
                Remark:
                  'Website: \u003ca href="https://www.amazon.com/s/ref=nb_sb_ss_c_3_8?url=search-alias%3Dcomputers\u0026field-keywords=gigabyte\u0026sprefix=gigabyte%2Caps%2C190" target="_blank"\u003ehttp://www.amazon.com\u003c/a\u003e',
                UrlPath: "https://www.amazon.com/gigabyte",
                GeoAxisX: 0,
                GeoAxisY: 0,
              },
              {
                Id: 52854,
                ImagePath: "/FileUpload/Reseller/52854.jpg",
                Name: "Best Buy",
                Tel: ["888-237-8289"],
                TelCountryCode: "1",
                Email: "",
                Address: "",
                ProductLines: [
                  "Motherboard",
                  "Graphics Card",
                  "Laptop",
                  "Monitors",
                ],
                Remark: "",
                UrlPath: "https://www.bestbuy.com/",
                GeoAxisX: 0,
                GeoAxisY: 0,
              },
              {
                Id: 98,
                ImagePath: "/FileUpload/Reseller/98.gif",
                Name: "Newegg",
                Tel: ["800390-1119"],
                TelCountryCode: "1",
                Email: "",
                Address: "17708 Rowland Street, City of Industry, CA 91748",
                ProductLines: [
                  "Motherboard",
                  "Graphics Card",
                  "Laptop",
                  "Monitors",
                  "BRIX (Mini-PC Barebone)",
                  "Keyboard",
                  "Mouse",
                  "PC Case",
                ],
                Remark: "",
                UrlPath:
                  "https://www.newegg.com/p/pl?d=gigabyte\u0026N=50001314%204841",
                GeoAxisX: 34.000885009765625,
                GeoAxisY: -117.91836547851563,
              },
              {
                Id: 83,
                ImagePath: "/FileUpload/Reseller/83.jpg",
                Name: "Allstarshop.com",
                Tel: ["800424-7188"],
                TelCountryCode: "1",
                Email: null,
                Address:
                  "30191A Avenida de las Banderas,                             Rancho Santa Margarita, CA 92688",
                ProductLines: ["Motherboard", "PC Case"],
                Remark:
                  'Website: \u003ca href="http://www.allstarshop.com/shop/Gigabyte_m058_p1.html" target="_blank"\u003ehttp://www.allstarshop.com\u003c/a\u003e\u003cbr\u003e\u003cbr\u003e',
                UrlPath: "",
                GeoAxisX: 33.6343147,
                GeoAxisY: -117.6035189,
              },
              {
                Id: 54726,
                ImagePath: "/FileUpload/Reseller/54726.png",
                Name: "AntOnline",
                Tel: [],
                TelCountryCode: "1",
                Email: "",
                Address: "",
                ProductLines: ["Motherboard", "Graphics Card", "Laptop"],
                Remark: "",
                UrlPath: "https://www.antonline.com/",
                GeoAxisX: 0,
                GeoAxisY: 0,
              },
              {
                Id: 27569,
                ImagePath: "/FileUpload/Reseller/27569.jpg",
                Name: "B\u0026H",
                Tel: ["8006066969"],
                TelCountryCode: "1",
                Email: "",
                Address: "420 9th Ave. at 34th St.  New York, NY 10001",
                ProductLines: ["Motherboard", "Laptop", "Monitors"],
                Remark:
                  'Website: \u003ca href="https://www.bhphotovideo.com/c/buy/Shop-by-Brand-Gigabyte/ci/4/phd/4254931964/N/4294255798?origSearch=gigabyte" target="_blank"\u003ehttp://www.bhphotovideo.com/\u003c/a\u003e',
                UrlPath: "",
                GeoAxisX: 40.752971649169922,
                GeoAxisY: -73.996429443359375,
              },
              {
                Id: 86,
                ImagePath: "/FileUpload/Reseller/86.jpg",
                Name: "Buy.com",
                Tel: [],
                TelCountryCode: "1",
                Email: null,
                Address: "85 Enterprise, Suite 100, Aliso Viejo, CA 92656",
                ProductLines: ["Motherboard", "PC Case"],
                Remark: "",
                UrlPath: "http://www.buy.com",
                GeoAxisX: 33.581233,
                GeoAxisY: -117.726467,
              },
              {
                Id: 87,
                ImagePath: "/FileUpload/Reseller/87.jpg",
                Name: "CDW",
                Tel: [],
                TelCountryCode: "1",
                Email: "",
                Address: "",
                ProductLines: ["Motherboard", "Graphics Card", "Laptop"],
                Remark: "",
                UrlPath: "https://www.cdw.com/",
                GeoAxisX: 42.228580474853516,
                GeoAxisY: -87.94403076171875,
              },
              {
                Id: 867,
                ImagePath: "/FileUpload/Reseller/867.png",
                Name: "Central Computers-Santa Clara",
                Tel: ["408-248-5888"],
                TelCountryCode: "1",
                Email: "",
                Address: "3777 Stevens Creek Blvd Santa Clara, CA 95051",
                ProductLines: ["Motherboard"],
                Remark:
                  'Website: \u003ca href="http://www.centralcomputers.com/search.aspx?SearchTerm=gigabyte\u0026section=-133942-" target="_blank"\u003ehttp://www.centralcomputers.com/\u003c/a\u003e\u003cbr\u003e\u003cbr\u003e',
                UrlPath: "",
                GeoAxisX: 37.324024200439453,
                GeoAxisY: -121.96800994873047,
              },
              {
                Id: 49467,
                ImagePath: "/FileUpload/Reseller/49467.jpg",
                Name: "Computer Upgrade King",
                Tel: ["800-985-9364"],
                TelCountryCode: "1",
                Email: null,
                Address:
                  "1555 Standing Ridge Drive, Suite A-1 Powhatan, VA 23159",
                ProductLines: ["Laptop"],
                Remark: "",
                UrlPath: "http://cukusa.com/",
                GeoAxisX: 37.5053829,
                GeoAxisY: -77.7414785,
              },
              {
                Id: 1014,
                ImagePath: "/FileUpload/Reseller/1014.jpg",
                Name: "EXcaliberPC.com",
                Tel: ["877-289-3972"],
                TelCountryCode: "1",
                Email: null,
                Address: "4221 Business Center Dr, Suite 4 Fremont, CA 94538",
                ProductLines: ["Laptop"],
                Remark: "",
                UrlPath: "http://www.excaliberpc.com",
                GeoAxisX: 37.505763,
                GeoAxisY: -121.953787,
              },
              {
                Id: 91,
                ImagePath: "/FileUpload/Reseller/91.jpg",
                Name: "Fry\u0027s Electronics",
                Tel: ["877-688-7678"],
                TelCountryCode: "1",
                Email: null,
                Address: "600 E. Brokaw Road, San Jose, CA 95112",
                ProductLines: ["BRIX (Mini-PC Barebone)"],
                Remark:
                  'Website: \u003ca href="http://www.frys.com/search?search_type=regular\u0026sqxts=1\u0026cat=\u0026query_string=gigabyte" target="_blank"\u003ehttp://www.frys.com\u003c/a\u003e\u003cbr\u003e\u003cbr\u003e',
                UrlPath: "",
                GeoAxisX: 37.38072,
                GeoAxisY: -121.9077499,
              },
              {
                Id: 47624,
                ImagePath: "/FileUpload/Reseller/47624.jpg",
                Name: "Gentech PC",
                Tel: ["800-990-7945"],
                TelCountryCode: "1",
                Email: null,
                Address: "1420 E. Cypress St Covina, CA 91724 United States",
                ProductLines: ["Laptop"],
                Remark: "",
                UrlPath: "http://www.gentechpc.com/",
                GeoAxisX: 34.0957789,
                GeoAxisY: -117.8607252,
              },
              {
                Id: 49617,
                ImagePath: "/FileUpload/Reseller/49617.jpg",
                Name: "HID Evolution",
                Tel: ["424-201-0350"],
                TelCountryCode: "1",
                Email: null,
                Address:
                  "2377 Crenshaw Blvd Ste 130, Torrance, California 90501 USA",
                ProductLines: ["Laptop"],
                Remark: "",
                UrlPath: "http://www.hidevolution.com/",
                GeoAxisX: 33.8238028,
                GeoAxisY: -118.3285294,
              },
              {
                Id: 52740,
                ImagePath: "/FileUpload/Reseller/52740.jpg",
                Name: "MichaelElectronics2",
                Tel: [],
                TelCountryCode: "",
                Email: "",
                Address: "9775 SW Commerce Circle, C3, Wilsonville, OR, 97070",
                ProductLines: ["Laptop"],
                Remark: "",
                UrlPath: "https://michaelelectronics2.com/",
                GeoAxisX: 45.336223602294922,
                GeoAxisY: -122.77719116210938,
              },
              {
                Id: 96,
                ImagePath: "/FileUpload/Reseller/96.jpg",
                Name: "Micro Center",
                Tel: ["614-326-8500"],
                TelCountryCode: "1",
                Email: "",
                Address: "",
                ProductLines: [
                  "Motherboard",
                  "Graphics Card",
                  "Laptop",
                  "Monitors",
                  "BRIX (Mini-PC Barebone)",
                  "PC Case",
                ],
                Remark:
                  'Website: \u003ca href="http://www.microcenter.com/search/search_results.aspx?N=4294965873" target="_blank"\u003ehttp://www.microcenter.com\u003c/a\u003e',
                UrlPath: "https://www.microcenter.com/",
                GeoAxisX: 40.060329437255859,
                GeoAxisY: -83.041343688964844,
              },
              {
                Id: 49719,
                ImagePath: "/FileUpload/Reseller/49719.jpg",
                Name: "Mobile Advance",
                Tel: ["888-995-5988"],
                TelCountryCode: "1",
                Email: null,
                Address: "203 Lemon Creek Dr. Unit D, Walnut, CA 91789",
                ProductLines: ["Laptop"],
                Remark: "",
                UrlPath: "http://www.mobileadvance.com/",
                GeoAxisX: 34.0114103,
                GeoAxisY: -117.8642879,
              },
              {
                Id: 49980,
                ImagePath: "/FileUpload/Reseller/49980.jpg",
                Name: "Outlet PC",
                Tel: ["702-262-7968"],
                TelCountryCode: "1",
                Email: null,
                Address: "7485 Commercial Way #160 Henderson, Nevada 89011",
                ProductLines: [
                  "Motherboard",
                  "Graphics Card",
                  "Keyboard",
                  "Mouse",
                ],
                Remark:
                  'Website: \u003ca href="http://www.outletpc.com/gigabyte-motherboards.html" target="_blank"\u003ehttp://www.outletpc.com\u003c/a\u003e\u003cbr\u003e\u003cbr\u003e',
                UrlPath: "",
                GeoAxisX: 36.05293,
                GeoAxisY: -115.024142,
              },
              {
                Id: 49812,
                ImagePath: "/FileUpload/Reseller/49812.jpg",
                Name: "PC RUSH",
                Tel: ["888-205-7777"],
                TelCountryCode: "1",
                Email: null,
                Address: "1325 E El Segundo Blvd. El Segundo, CA 90245",
                ProductLines: [
                  "Motherboard",
                  "Graphics Card",
                  "BRIX (Mini-PC Barebone)",
                  "Mouse",
                  "PC Case",
                ],
                Remark:
                  'Website: \u003ca href="http://www.pcrush.com/store/365/GIGABYTE" target="_blank"\u003ehttp://www.pcrush.com/\u003c/a\u003e',
                UrlPath: "",
                GeoAxisX: 33.9167874,
                GeoAxisY: -118.4013349,
              },
              {
                Id: 52852,
                ImagePath: "/FileUpload/Reseller/52852.jpg",
                Name: "Platinum Micro",
                Tel: [],
                TelCountryCode: "",
                Email: "",
                Address: "",
                ProductLines: ["Laptop"],
                Remark: "",
                UrlPath: "https://platinummicro.com/",
                GeoAxisX: 0,
                GeoAxisY: 0,
              },
              {
                Id: 604,
                ImagePath: "/FileUpload/Reseller/604.gif",
                Name: "QuietPCusa.com",
                Tel: ["530-274-7766"],
                TelCountryCode: "1",
                Email: null,
                Address:
                  "Quiet PC USA, P.O. Box 288, Chicago Park, California, 95712",
                ProductLines: ["PC Case"],
                Remark: "",
                UrlPath: "http://www.quietpcusa.com/",
                GeoAxisX: 0,
                GeoAxisY: 0,
              },
              {
                Id: 51160,
                ImagePath: "/FileUpload/Reseller/51160.jpg",
                Name: "Walmart",
                Tel: ["800-925-6278"],
                TelCountryCode: "1",
                Email: null,
                Address: "702 SW 8th St., Bentonville, AR 72716",
                ProductLines: ["Motherboard"],
                Remark: "1-800-WALMART",
                UrlPath: "http://www.walmart.com/",
                GeoAxisX: 36.3655837,
                GeoAxisY: -94.2181498,
              },
              {
                Id: 52853,
                ImagePath: "/FileUpload/Reseller/52853.jpg",
                Name: "Walmart.com",
                Tel: [],
                TelCountryCode: "",
                Email: "",
                Address: "",
                ProductLines: ["Laptop"],
                Remark: "",
                UrlPath: "https://www.walmart.com/",
                GeoAxisX: 0,
                GeoAxisY: 0,
              },
              {
                Id: 49841,
                ImagePath: "/FileUpload/Reseller/49841.jpg",
                Name: "Wiston Group",
                Tel: ["909-444-8214"],
                TelCountryCode: "1",
                Email: null,
                Address: "713 Brea Canyon Rd, Walnut CA 91789",
                ProductLines: ["Motherboard"],
                Remark: "",
                UrlPath: "http://www.wistongroup.com/",
                GeoAxisX: 34.0048048,
                GeoAxisY: -117.8483677,
              },
            ],
          };
        }

        return {
          NowPage: 1,
          NowSaleType: "3",
          TotalPage: 1,
          ListItems: [
            {
              Id: 47192,
              ImagePath: "/FileUpload/Reseller/47192.jpg",
              Name: "Altex",
              Tel: ["210-655-8882"],
              TelCountryCode: "1",
              Email: null,
              Address: "11342 IH35 North San Antonio, TX 78233",
              ProductLines: ["Motherboard"],
              Remark:
                'Website: \u003ca href="https://www.altex.com/AdvancedSearchE.aspx?k=gigabyte" target="_blank"\u003ehttp://www.altex.com/\u003c/a\u003e',
              UrlPath: "",
              GeoAxisX: 29.560052,
              GeoAxisY: -98.3636131,
            },
            {
              Id: 54726,
              ImagePath: "/FileUpload/Reseller/54726.png",
              Name: "AntOnline",
              Tel: [],
              TelCountryCode: "1",
              Email: "",
              Address: "",
              ProductLines: ["Motherboard", "Graphics Card", "Laptop"],
              Remark: "",
              UrlPath: "https://www.antonline.com/",
              GeoAxisX: 0,
              GeoAxisY: 0,
            },
            {
              Id: 867,
              ImagePath: "/FileUpload/Reseller/867.png",
              Name: "Central Computers-Santa Clara",
              Tel: ["408-248-5888"],
              TelCountryCode: "1",
              Email: "",
              Address: "3777 Stevens Creek Blvd Santa Clara, CA 95051",
              ProductLines: ["Motherboard"],
              Remark:
                'Website: \u003ca href="http://www.centralcomputers.com/search.aspx?SearchTerm=gigabyte\u0026section=-133942-" target="_blank"\u003ehttp://www.centralcomputers.com/\u003c/a\u003e\u003cbr\u003e\u003cbr\u003e',
              UrlPath: "",
              GeoAxisX: 37.324024200439453,
              GeoAxisY: -121.96800994873047,
            },
            {
              Id: 91,
              ImagePath: "/FileUpload/Reseller/91.jpg",
              Name: "Fry\u0027s Electronics",
              Tel: ["877-688-7678"],
              TelCountryCode: "1",
              Email: null,
              Address: "600 E. Brokaw Road, San Jose, CA 95112",
              ProductLines: ["BRIX (Mini-PC Barebone)"],
              Remark:
                'Website: \u003ca href="http://www.frys.com/search?search_type=regular\u0026sqxts=1\u0026cat=\u0026query_string=gigabyte" target="_blank"\u003ehttp://www.frys.com\u003c/a\u003e\u003cbr\u003e\u003cbr\u003e',
              UrlPath: "",
              GeoAxisX: 37.38072,
              GeoAxisY: -121.9077499,
            },
            {
              Id: 96,
              ImagePath: "/FileUpload/Reseller/96.jpg",
              Name: "Micro Center",
              Tel: ["614-326-8500"],
              TelCountryCode: "1",
              Email: "",
              Address: "",
              ProductLines: [
                "Motherboard",
                "Graphics Card",
                "Laptop",
                "Monitors",
                "BRIX (Mini-PC Barebone)",
                "PC Case",
              ],
              Remark:
                'Website: \u003ca href="http://www.microcenter.com/search/search_results.aspx?N=4294965873" target="_blank"\u003ehttp://www.microcenter.com\u003c/a\u003e',
              UrlPath: "https://www.microcenter.com/",
              GeoAxisX: 40.060329437255859,
              GeoAxisY: -83.041343688964844,
            },
            {
              Id: 253,
              ImagePath: "/FileUpload/Reseller/253.jpg",
              Name: "Milwaukee PC",
              Tel: ["414332-0874"],
              TelCountryCode: "1",
              Email: null,
              Address: "3900 N. Sherburn Place, Shorewood, WI 53211",
              ProductLines: ["Motherboard"],
              Remark: "",
              UrlPath: "http://www.milwaukeepc.com",
              GeoAxisX: 43.0884352,
              GeoAxisY: -87.8953438,
            },
          ],
        };
      }

      if (ProductType === ProductTypeEnum.enterprise) {
        return {
          NowPage: 1,
          NowSaleType: "4,2",
          TotalPage: 1,
          ListItems: [
            {
              Id: 48926,
              ImagePath: "/FileUpload/Reseller/48926.png",
              Name: "Newegg Business",
              Tel: ["(888) 482-6678"],
              TelCountryCode: "1",
              Email: "sales@neweggbusiness.com",
              Address: "",
              ProductLines: [
                "Server Motherboard",
                "R Series",
                "H Series",
                "G Series",
                "E Series",
                "S Series",
                "W Series",
                "Accessory",
              ],
              Remark: "",
              UrlPath: "https://www.gigabyte.com/us/WheretoBuy/Enterprise",
              GeoAxisX: 34.017429351806641,
              GeoAxisY: -118.05129241943359,
            },
            {
              Id: 52985,
              ImagePath: "/FileUpload/Reseller/52985.jpg",
              Name: "Advanced HPC",
              Tel: ["858-716-8224"],
              TelCountryCode: "1",
              Email: "Sales@advancedhpc.com",
              Address: "8228 Mercury Court Suite 100 San Diego, CA 92111",
              ProductLines: [
                "Server Motherboard",
                "R Series",
                "H Series",
                "G Series",
                "E Series",
                "S Series",
                "W Series",
                "Accessory",
              ],
              Remark: "",
              UrlPath: "http://www.advancedhpc.com",
              GeoAxisX: 32.835624694824219,
              GeoAxisY: -117.14720153808594,
            },
            {
              Id: 52973,
              ImagePath: "/FileUpload/Reseller/52973.png",
              Name: "Applied Data Systems",
              Tel: ["844-371-4949"],
              TelCountryCode: "1",
              Email: "info@applieddatasystems.com",
              Address: "12180 Dearborn PL Poway, CA 92064",
              ProductLines: [
                "R Series",
                "H Series",
                "G Series",
                "E Series",
                "S Series",
                "Accessory",
              ],
              Remark: "",
              UrlPath: "https://applieddatasystems.com/",
              GeoAxisX: 32.937419891357422,
              GeoAxisY: -117.0380859375,
            },
            {
              Id: 84,
              ImagePath: "/FileUpload/Reseller/84.gif",
              Name: "ASI",
              Tel: ["800-2000274"],
              TelCountryCode: "1",
              Email: "",
              Address: "48289 Fremont Blvd., Fremont, CA 94538",
              ProductLines: [
                "Server Motherboard",
                "R Series",
                "H Series",
                "G Series",
                "E Series",
                "S Series",
                "W Series",
                "Embedded Computing",
                "Accessory",
              ],
              Remark: "",
              UrlPath: "http://www.asipartner.com/",
              GeoAxisX: 37.468280792236328,
              GeoAxisY: -121.93682098388672,
            },
            {
              Id: 53428,
              ImagePath: "/FileUpload/Reseller/53428.png",
              Name: "Aspen Systems",
              Tel: ["303-431-4606"],
              TelCountryCode: "1",
              Email: "sales@aspsys.com",
              Address: "3900 Youngfield  Street, Wheat Ridge, CO, 80033-3865",
              ProductLines: [
                "Server Motherboard",
                "R Series",
                "H Series",
                "G Series",
                "E Series",
                "S Series",
                "W Series",
                "Accessory",
              ],
              Remark: "",
              UrlPath: "https://www.aspsys.com/",
              GeoAxisX: 39.768272399902344,
              GeoAxisY: -105.14222717285156,
            },
            {
              Id: 53429,
              ImagePath: "/FileUpload/Reseller/53429.png",
              Name: "Atipa",
              Tel: ["785-841-9559"],
              TelCountryCode: "1",
              Email: "sales@atipa.com",
              Address: "4921 Legends Drive, Lawrence, KS 66049",
              ProductLines: [
                "Server Motherboard",
                "R Series",
                "H Series",
                "G Series",
                "E Series",
                "S Series",
                "W Series",
                "Accessory",
              ],
              Remark: "",
              UrlPath: "http://www.atipa.com/",
              GeoAxisX: 38.962211608886719,
              GeoAxisY: -95.3093490600586,
            },
            {
              Id: 53436,
              ImagePath: "/FileUpload/Reseller/53436.png",
              Name: "Ciara",
              Tel: ["480-626-9000"],
              TelCountryCode: "1",
              Email: "alex.chowdhury@hypertec.com",
              Address: "1868 E. Broadway Rd., Tempe, AZ 85282",
              ProductLines: [
                "Server Motherboard",
                "R Series",
                "H Series",
                "G Series",
                "E Series",
                "S Series",
                "W Series",
                "Accessory",
              ],
              Remark: "",
              UrlPath: "http://ciaratech.com/",
              GeoAxisX: 33.4086799621582,
              GeoAxisY: -111.90645599365234,
            },
            {
              Id: 53451,
              ImagePath: "/FileUpload/Reseller/53451.png",
              Name: "Exxact",
              Tel: ["510-226-7366"],
              TelCountryCode: "1",
              Email: "sales@exxactcorp.com",
              Address: "46221 Landing Parkway, Fremont, CA 94538",
              ProductLines: [
                "Server Motherboard",
                "R Series",
                "H Series",
                "G Series",
                "E Series",
                "S Series",
                "W Series",
                "Accessory",
              ],
              Remark: "",
              UrlPath: "http://www.exxactcorp.com/",
              GeoAxisX: 37.488327026367188,
              GeoAxisY: -121.94473266601563,
            },
            {
              Id: 52599,
              ImagePath: "/FileUpload/Reseller/52599.png",
              Name: "GIGABYTE USA",
              Tel: ["626-854-9338"],
              TelCountryCode: "1",
              Email: "",
              Address: "17358 Railroad Street, City of Industry CA 91748",
              ProductLines: [
                "Server Motherboard",
                "R Series",
                "H Series",
                "G Series",
                "E Series",
                "S Series",
                "W Series",
                "Data Center - OCP",
                "Accessory",
              ],
              Remark:
                "\u003cb\u003eU.S.A. Sales Contact for GIGABYTE Enterprise Hardware\u003c/b\u003e\u003cbr\u003eChen Lee: +1(626) 854-9338 x1180\u003cbr\u003echenlee@gigabyteusa.com\u003cbr\u003eVictoria Kung: +886-2-8912-4000 x1277\u003cbr\u003evictoria.kung@gigabyte.com",
              UrlPath: "https://www.gigabyte.com/Enterprise",
              GeoAxisX: 34.002853393554688,
              GeoAxisY: -117.92837524414063,
            },
            {
              Id: 52739,
              ImagePath: "/FileUpload/Reseller/52739.png",
              Name: "ICC-USA",
              Tel: ["877 422 8729"],
              TelCountryCode: "1",
              Email: "",
              Address: "300 Wainwright Drive, Northbrook, IL 60062, USA",
              ProductLines: [
                "Server Motherboard",
                "R Series",
                "H Series",
                "G Series",
                "S Series",
                "W Series",
                "Accessory",
              ],
              Remark: "",
              UrlPath: "http://www.icc-usa.com/",
              GeoAxisX: 42.148647308349609,
              GeoAxisY: -87.859481811523438,
            },
            {
              Id: 543,
              ImagePath: "/FileUpload/Reseller/543.jpg",
              Name: "Ingram Micro",
              Tel: ["800-456-8000"],
              TelCountryCode: "1",
              Email: "",
              Address: "1600 E. St. Andrew Place, Snta Ana, CA 92705-4926",
              ProductLines: [
                "Server Motherboard",
                "R Series",
                "H Series",
                "G Series",
                "E Series",
                "S Series",
                "W Series",
                "Embedded Computing",
                "Accessory",
              ],
              Remark: "",
              UrlPath: "http://www.ingrammicro.com",
              GeoAxisX: 33.722396850585938,
              GeoAxisY: -117.84828186035156,
            },
            {
              Id: 53433,
              ImagePath: "/FileUpload/Reseller/53433.png",
              Name: "MBX",
              Tel: ["800-560-1195"],
              TelCountryCode: "1",
              Email: "",
              Address: "1200 Technology Way, Libertyville, IL 60048",
              ProductLines: [
                "Server Motherboard",
                "R Series",
                "H Series",
                "G Series",
                "S Series",
                "W Series",
                "Accessory",
              ],
              Remark: "",
              UrlPath: "http://www.mbx.com/",
              GeoAxisX: 42.297348022460938,
              GeoAxisY: -87.996246337890625,
            },
            {
              Id: 53432,
              ImagePath: "/FileUpload/Reseller/53432.png",
              Name: "Nor-Tech",
              Tel: ["952-808-1000"],
              TelCountryCode: "1",
              Email: "INFO@WWW.NOR-TECH.COM",
              Address: "901 Cliff Rd E., Burnsville, MN 55337",
              ProductLines: [
                "Server Motherboard",
                "R Series",
                "H Series",
                "G Series",
                "S Series",
                "W Series",
                "Accessory",
              ],
              Remark: "",
              UrlPath: "http://www.nor-tech.com/company-info/",
              GeoAxisX: 44.789283752441406,
              GeoAxisY: -93.2635498046875,
            },
            {
              Id: 141,
              ImagePath: "/FileUpload/Reseller/141.jpg",
              Name: "Rackmountpro",
              Tel: ["800-526-8650"],
              TelCountryCode: "1",
              Email: null,
              Address: "595 Yorbita Road, La Puente CA 91744",
              ProductLines: [
                "R Series",
                "H Series",
                "G Series",
                "E Series",
                "Accessory",
              ],
              Remark: "",
              UrlPath: "https://www.rackmountpro.com/",
              GeoAxisX: 34.006744384765625,
              GeoAxisY: -117.90501403808594,
            },
            {
              Id: 52979,
              ImagePath: "/FileUpload/Reseller/52979.png",
              Name: "Red Barn ",
              Tel: ["800-796-8809"],
              TelCountryCode: "1",
              Email: "sales@thinkredbarn.com",
              Address: "37 Pine Street, Binghamton NY 13901",
              ProductLines: [
                "R Series",
                "H Series",
                "G Series",
                "E Series",
                "S Series",
                "W Series",
                "Accessory",
              ],
              Remark: "",
              UrlPath: "https://redbarnhpc.com/",
              GeoAxisX: 42.101482391357422,
              GeoAxisY: -75.904991149902344,
            },
            {
              Id: 52212,
              ImagePath: "/FileUpload/Reseller/52212.jpg",
              Name: "Spectrum Servers",
              Tel: ["800-526-8650"],
              TelCountryCode: "1",
              Email: "",
              Address: "595 Yorbita Road, La Puente CA 91744",
              ProductLines: [
                "R Series",
                "H Series",
                "G Series",
                "E Series",
                "Accessory",
              ],
              Remark: "",
              UrlPath: "http://www.spectrumservers.com/",
              GeoAxisX: 34.0067138671875,
              GeoAxisY: -117.90499114990234,
            },
            {
              Id: 53434,
              ImagePath: "/FileUpload/Reseller/53434.png",
              Name: "System76",
              Tel: ["720-226-9269"],
              TelCountryCode: "1",
              Email: "contact@system76.com",
              Address: "4240 Carson St. Suite 101, Denver, CO 80239",
              ProductLines: ["R Series", "Accessory"],
              Remark: "",
              UrlPath: "http://system76.com/servers",
              GeoAxisX: 39.774295806884766,
              GeoAxisY: -104.82859039306641,
            },
            {
              Id: 52880,
              ImagePath: "/FileUpload/Reseller/52880.png",
              Name: "Thinkmate",
              Tel: ["800-371-1212"],
              TelCountryCode: "1",
              Email: "tmsales@thinkmate.com",
              Address: "159 Overland Rd Waltham Massachusetts 02451",
              ProductLines: [
                "R Series",
                "H Series",
                "G Series",
                "E Series",
                "S Series",
                "W Series",
                "Accessory",
              ],
              Remark: "",
              UrlPath: "https://www.thinkmate.com",
              GeoAxisX: 42.377326965332031,
              GeoAxisY: -71.25909423828125,
            },
          ],
        };
      }
    }

    return {
      NowPage: 1,
      NowSaleType: "1",
      TotalPage: 1,
      ListItems: [],
    };
  }
);
